### ISSUE TITLE
No lunch appears in RP after tests execution

### ISSUE THREAD

**Issue by wsbaser** [reportportal/example-net-vstest#2]
Downloaded, specified my Authentication token and project name, executed tests. No results in RP.
example-net-nunit works fine

**Comment by wsbaser** [comment]
rp.epam.com has version 4 that is not supported by the latest version of the agent

**Comment by bhargavkumar-65** [comment]
@nvborisenko  @wsbaser  I am still facing this issue. Downloaded this repository and updated Reportportal configuration 
with url:"localhost:8080/api/v1/", and project nanme, token provided.
But no tests are recorded in reportportal after executing the tests from TestExplorer. please let me know if i am missing something.

**Comment by nvborisenko** [comment]
Hopefully this your case https://github.com/reportportal/agent-net-vstest/issues/27
