### ISSUE TITLE
Friendly Logger ReportPortal not Found on Successful Build

### ISSUE THREAD

**Issue by bhargavkumar-65** [reportportal/example-net-vstest#3]
Hi rp team,
thanks for great sample example project, 
Im facing below issue when i try to run the sample project. Please help.
![image](https://user-images.githubusercontent.com/3831436/124266721-f17a6c00-db54-11eb-89ff-8621d1b2285c.png)

![image](https://user-images.githubusercontent.com/3831436/124268282-efb1a800-db56-11eb-8a8d-c198a3606400.png)

**Comment by nvborisenko** [comment]
Similar issue https://github.com/reportportal/agent-net-vstest/issues/27
